# This workflow will keep secrets varaibles
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GreenPy Workflow

jobs:
	test_env:
		environment: TEST_SECRET
		runs-on: ubuntu-latest
	steps:
	- name: Set up Python
	uses: actions/setup-python@v2
	with:
		python-version: 3.8
        
	- name: Test env vars for python
	run: python -c 'import os;print(os.environ)'
	env:
		G_KEY: ${{ secrets.G_KEY }} 
		G_MAIL ${{ secrets.G_MAIL }} 