name: GreenPy

on: push

jobs:
  test_env:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: execute py script # email-from-python.py
      env:
        ENV_SECRET: ${{ secrets.ENV_SECRET }}
        REPO_SECRET: ${{ secrets.REPO_SECRET }}
      run: python app.py
